### ISSUE TITLE
Behaviors in this state is not translated

### ISSUE THREAD

**Issue by anon1231823** [Legacy-of-Sylvanaar/wow-instant-messenger#53]
**Describe the bug**
It's translated in esES/esMX but still shows english

**To Reproduce**
See screenshot

**Expected behavior**
Should be ["Behaviors for state:"] = "Comportamientos de estado:"

**Screenshots**
![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/67269448/ee37d652-fd27-49bb-9f89-227c0543a2b2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pazza** [comment]
I merged your translations

**Comment by anon1231823** [comment]
@Pazza that doesn't fix the problem. The addon isn't looking for that string
![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/67269448/acb8be45-ec70-4d53-8526-b7cbc8cd1d10)

**Comment by Pazza** [comment]
Should be fixed in 3.10.18
